### ISSUE TITLE
automated pull from Austin Socrata feed

### ISSUE THREAD

**Issue by rskoenig** [civinomics/city-council#148] opened 2017-06-01 21:54 UTC
As City Staff, I want meetings to auto-populate, so that I don't have to spend a lot of time trying a new tool.

**Comment by drew-moore** [comment] 2017-06-14 19:39
Is this a dupe of #12 or are you thinking of something beyond that?

**Comment by rskoenig** [comment] 2017-06-14 20:53
Added #12 to Sprint 7

**Closed** 2017-06-14 20:53 UTC
Labels: must do, type: user story
