### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by rskoenig** [civinomics/city-council#42] opened 2017-02-22 16:56 UTC
As a Citizen,
I want to log in to Civinomics,
so that I can participate in the latest meetings for my local government.

**Comment by drew-moore** [comment] 2017-02-22 22:53
closed as dupe of #2

**Comment by rskoenig** [comment] 2017-04-19 18:00
Not a dupe at all in fact. I still can't login, even though I can sign up.

**Closed** 2017-04-21 18:05 UTC
Labels: duplicate, must do, P2: required, type: user story
